seed: 0
# could go lower, but 1 second per request to avoid spamming
delay: 1
model: gpt-3.5-turbo-1106
max_tokens: 1024
temperature: 1.0
top_p: 0.7
system_prompt: >-
  You are an expert linguistic assistant.
  You will be tasked with explaining why a tweet may have a stance towards a provided target or topic.
  You should discuss your reasoning in detail, thinking step-by-step.
user_prompt: |-
  Tweet:
  {post}
  Frame:
  {frame}
  Stance: {stance}
