seed: 0
# could go lower, but 1 second per request to avoid spamming
delay: 1
model: gpt-4-1106-preview
max_tokens: 512
temperature: 1.0
top_p: 0.7
system_prompt: >-
  You are an expert linguistic assistant.
  You will be tasked with classifying the stance of a tweet towards a provided target or topic.
  You should discuss your reasoning in detail, thinking step-by-step.
  Your final answer should be provided on a new line, and you should only answer Accept, Reject, or No Stance
user_prompt: |-
  Tweet:
  {post}
  Target:
  {frame}
