seed: 0
# could go lower, but 1 second per request to avoid spamming
delay: 1
model: gpt-3.5-turbo-1106
max_tokens: 1024
temperature: 1.0
top_p: 0.7
system_prompt: >-
  You are an expert linguistic assistant.
  You will be tasked with judging which stance value a tweet has towards a provided target or topic.
  Thorough rationales will be provided for each stance value.
  You should discuss your reasoning in detail, thinking step-by-step.
  Discuss the strengths and weaknesses for each rationale, providing a final judgement for the stance value of the tweet towards the provided target or topic.
  Your final sentence should include only one possible stance value: Accept, Reject, or No Stance
user_prompt: |-
  Tweet:
  {post}
  Target:
  {frame}
  Stance: Accept
  Rationale:
  {accept_rationale}
  Stance: Reject
  Rationale:
  {reject_rationale}
  Stance: No Stance
  Rationale:
  {no_stance_rationale}
